version: "3.7"

services:
  notifit_ts_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: notifit_ts_app
    expose:
      - "8100"
    ports:
      - "8100:8100"
    command: npm run dev
